# C: Line is too long.
LineLength:
  Enabled: false

# C: Missing top-level class documentation comment.
Documentation:
  Enabled: false

# C: Use only ascii symbols in comments.
AsciiComments:
  Enabled: false

# C: Method has too many lines.
Style/MethodLength:
  Exclude:
    - db/migrate/*

# Ignore files.
AllCops:
  Exclude:
    - vendor/**/*
    - spec/dummy/db/schema.rb
